### PR TITLE
Add a nice passwords.txt to be included

### PR DESCRIPTION
**Pull request by spmedia**
Add in the top 304k passwords from the [Probable Passwords list project](https://github.com/berzerk0/Probable-Wordlists) to be included by default to give new users or beginners a good list to start with. It's sourced from many different database breaches and combo lists (rockyou is one of them).

### CODE REVIEW

**Comment by llebout** [comment]
Thanks for the PR!

I would rather not clutter the git repository with big files such as this, do you mind if we put a link to that password list in the README instead?

**Comment by spmedia** [comment]
Yeah that works too

**Comment by llebout** [comment]
Great! Want to update your PR with that so I can merge it?

**Comment by llebout** [comment]
Done in https://github.com/leo-lb/wpbrute-rs/commit/9c0d480cbf790814432eca0ce49f4dc3562ca15e

**Pull request closed without merging**
